server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: xc_cms
  freemarker:
    settings:
      template_update_delay: 0

  rabbitmq:
    host: 132.232.117.84
    username: guest
    password: guest
    template:
      retry:
        enabled: true
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:50101/eureka/
    registry-fetch-interval-seconds: 10 #从eureka服务器注册表中获取注册信息的时间间隔
    instance-info-replication-interval-seconds: 20 #发送实例变化信息到eureka服务器所需要的时间间隔
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
    instance-id: ${eureka.instance.ip-address}-${spring.application.name}:${server.port}
    ip-address: 127.0.0.1
    prefer-ip-address: true